id = "me.loaforc.questpinning"
name = "QuestPinning"
description = "A simple QOL mod that lets you pin quests to the main hud."
version = "1.0.4"
homepage = "https://github.com/LoafOrc"
author = "loaforc"

icon = "thunderstore/icon.png"
readme = "README.md"
# changelog = "CHANGELOG.md"

# both are optional here, pick what you want
[project]
csharp = "./QuestPinning/QuestPinning.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"